# .rubocop.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/services/**/*'

Layout/LineLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15